name: Test pull_request_comment event
on:
  pull_request_review_comment:
    types: [created, edited]
  pull_request:

jobs:
  test_features:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I was edited"

