name: Test pull_request_comment event
on:
  pull_request_review_comment:
    types: [created, edited]

jobs:
  test_features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/anvil-reminders
        with:
          token: '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'

